.. code-block:: javascript

    {
      "docs": [{
        "foo": 1,
        "bar": "98",
        "_id": "67ddcbee-9bae-4e70-9ad8-eb8ee608c8d3",
        "_attachments": {
    
        }
      }, {
        "foo": 2,
        "bar": "99",
        "_id": "4c3283cf-8fbd-4d63-af6e-0eafb77a7903",
        "_attachments": {
    
        }
      }, {
        "foo": 3,
        "bar": "100",
        "_id": "40383277-e0cf-42f3-8f44-7c265bf92030",
        "_attachments": {
    
        }
      }]
    }
