.. code-block:: javascript

    {
      "docs": [{
        "name": "Nicholas",
        "age": 45,
        "gender": "male",
        "_id": "96f898f0-f6ff-4a9b-aac4-503992f31b01",
        "_attachments": {
    
        }
      }, {
        "name": "Taylor",
        "age": 50,
        "gender": "male",
        "_id": "5a049246-179f-42ad-87ac-8f080426c17c",
        "_attachments": {
    
        }
      }, {
        "name": "Owen",
        "age": 51,
        "gender": "male",
        "_id": "d1f61e66-7708-4da6-aa05-7cbc33b44b7e",
        "_attachments": {
    
        }
      }]
    }
