.. code-block:: http

    200 OK
    Cache-Control: must-revalidate
    Content-Length: 42
    Content-Type: text/plain; charset=UTF-8
    Date: Mon, 04 Mar 2013 14:06:11 GMT
    server: CouchDB/1.0.2 (Erlang OTP/R14B)
    Set-Cookie: AuthSession="a2ltc3RlYmVsOjUxMzRBQTUzOtiY2_IDUIdsTJEVNEjObAbyhrgz"; Expires=Tue, 05 Mar 2013 14:06:11 GMT; Max-Age=86400; Path=/; HttpOnly; Version=1
    x-couch-request-id: a638431d

