.. code-block:: javascript

    {
      "update_seq": "0-g1AAAADneJzLYWBgYMlgTmFQSElKzi9KdUhJMtbLTS3KLElMT9VLzskvTUnMK9HLSy3JAapkSmRIsv___39WIgOqHkM8epIcgGRSPTZt-KzKYwGSDA1ACqhzP0k2QrQegGgF2ZoFAGdBTTo",
      "db_name": "db",
      "purge_seq": 0,
      "other": {
        "data_size": 0
      },
      "doc_del_count": 0,
      "doc_count": 0,
      "disk_size": 316,
      "disk_format_version": 5,
      "compact_running": false,
      "instance_start_time": "0"
    }
