.. code-block:: javascript

    {
      "_id": "DocID",
      "_rev": "3-aedfb06537c1d77a087eb295571f7fc9",
      "name": "Anna",
      "age": 89,
      "gender": "female",
      "_revs_info": [{
        "rev": "3-aedfb06537c1d77a087eb295571f7fc9",
        "status": "available"
      }, {
        "rev": "2-f29c836d0bedc4b4b95cfaa6d99e95df",
        "status": "available"
      }, {
        "rev": "1-2b458b0705e3007bce80b0499a1199e7",
        "status": "available"
      }]
    }
