.. code-block:: javascript

    {
      "_id": "DocID",
      "_rev": "2-f29c836d0bedc4b4b95cfaa6d99e95df",
      "name": "Anna",
      "age": 89,
      "gender": "female",
      "_attachments": {
        "my attachment": {
          "content_type": "application/json; charset=UTF-8",
          "revpos": 2,
          "digest": "md5-37IZysiyWLRWx31J/1WQHw==",
          "length": 12,
          "stub": true
        }
      }
    }
