.. code-block:: javascript

    {
      "total_rows": 2,
      "bookmark": "g2wAAAABaANkACBkYmNvcmVAZGI3Lm1lcml0YWdlLmNsb3VkYW50Lm5ldGwAAAACYkAAAABif____2poAkY_8AAAAAAAAGEBag",
      "rows": [{
        "id": "6b9e47bd-b09b-4458-b49b-e8032057f26b",
        "order": [1.0, 0],
        "fields": {
          "default": "bcd"
        }
      }, {
        "id": "54b4ef51-d0cb-44c2-aa55-789370c26d87",
        "order": [1.0, 1],
        "fields": {
          "default": "bbb"
        }
      }]
    }
