.. code-block:: javascript

    {
      "total_rows": 3,
      "bookmark": "g1AAAACWeJzLYWBgYMpgTmFQSElKzi9KdUhJMtbLTS3KLElMT9VLzskvTUnMK9HLSy3JAalMcgCSSfX____PAvPdQHwQSGTIIt6UPBaQlgNA6j_CJPsPcJOyANNEKzY",
      "rows": [{
        "id": "dd828eb4-c3f1-470f-aeff-c375ef70e4ad",
        "order": [0.0, 1],
        "fields": {
          "default": "aa",
          "foo": 0.0
        }
      }, {
        "id": "ea522cf1-eb8e-4477-aa92-d1fa459bb216",
        "order": [1.0, 0],
        "fields": {
          "default": "ab",
          "foo": 1.0
        }
      }, {
        "id": "c838baed-d573-43ea-9c34-621cf0f13301",
        "order": [2.0, 0],
        "fields": {
          "default": "ac",
          "foo": 2.0
        }
      }]
    }
