.. code-block:: javascript

    {
      "results": [{
        "total_rows": 3,
        "offset": 0,
        "rows": [{
          "id": "8fbb1250-6908-42e0-8862-aef60dc430a2",
          "key": 0,
          "value": {
            "_id": "8fbb1250-6908-42e0-8862-aef60dc430a2",
            "_rev": "1-ad1680946839206b088da5d9ac01e4ef",
            "foo": 0,
            "bar": "foo"
          }
        }, {
          "id": "d69fb42c-b3b1-4fae-b2ac-55a7453b4e41",
          "key": 1,
          "value": {
            "_id": "d69fb42c-b3b1-4fae-b2ac-55a7453b4e41",
            "_rev": "1-abb9a4fc9f0f339efbf667ace66ee6a0",
            "foo": 1,
            "bar": "bar"
          }
        }, {
          "id": "d1fa85cd-cd18-4790-8230-decf99e1f60f",
          "key": 2,
          "value": {
            "_id": "d1fa85cd-cd18-4790-8230-decf99e1f60f",
            "_rev": "1-d075a71f2d47af7d4f64e4a367160e2a",
            "foo": 2,
            "bar": "baz"
          }
        }]
      }, {
        "total_rows": 3,
        "offset": 1,
        "rows": [{
          "id": "d69fb42c-b3b1-4fae-b2ac-55a7453b4e41",
          "key": 1,
          "value": {
            "_id": "d69fb42c-b3b1-4fae-b2ac-55a7453b4e41",
            "_rev": "1-abb9a4fc9f0f339efbf667ace66ee6a0",
            "foo": 1,
            "bar": "bar"
          }
        }, {
          "id": "d1fa85cd-cd18-4790-8230-decf99e1f60f",
          "key": 2,
          "value": {
            "_id": "d1fa85cd-cd18-4790-8230-decf99e1f60f",
            "_rev": "1-d075a71f2d47af7d4f64e4a367160e2a",
            "foo": 2,
            "bar": "baz"
          }
        }]
      }]
    }
